### ISSUE TITLE
allow changing http and https port

### ISSUE THREAD

**Issue by maxadamo** [theforeman/puppet-pulp#326] opened 2018-07-09 08:58 UTC
could you please allow to change http/https ports? 
see pull request:  [#325](https://github.com/theforeman/puppet-pulp/pull/325)

**Please Note**: 
2 tests out of 3 were successful, but - unless I'm overlooking - I don't think that the 3rd test has anything to do with my change. To me, it seems that your Travis test is a bit spoiled :-) 
May I suggest you to use PDK?

**Comment by ekohl** [comment] 2018-07-09 10:58
The acceptance test is failing because of a regression. https://github.com/pulp/pulp/commit/81741bcc737867b31d7617c46b407c6280130528 has been merged but needs to be released.

I haven't had time yet to look at PDK. We already use the same gems that PDK would pull in so it hasn't really been a priority. https://github.com/theforeman/foreman-installer-modulesync has served us well enough but we're open to patches.

**Comment by maxadamo** [comment] 2018-07-09 11:00
thanks for the explanation :+1:

**Closed** 2018-07-09 11:01 UTC
